### ISSUE TITLE
domain  and Subdomin

### ISSUE THREAD

**Issue by koloner** [suuhm/unblock-proxy.sh#9] opened 2024-01-21 15:13 UTC
Good time, thank you for this very good project

I need to proxy a domain and all its subdomains, how should I add it in the file or in the web panel?
Or how can all incoming requests be proxyed and there is no need to set the domain

**Comment by suuhm** [comment] 2024-01-21 19:39
Hey yes its ez for the smartdns mode like just adding `yourdomain.com` in the web interface.

For transparent mode your need first enumerate all subdomains with tools like subfind3r oder dnscan or nmap

Like: `python sublist3r.py -d yourdomain.com`

**Comment by koloner** [comment] 2024-01-21 20:01
Yes, I easily add the domains, but when I confirm the settings to be applied, it encounters an error, and after I add the domains once, it is completely disabled and gives this error every time.
`dnsmasq[12610]: exiting on receipt of SIGTERM`
I checked and explained that port 53 is being used, which is using
`sudo kill -9 $ (sudo lsof -t -i:53)`
I close the whole process, but when I run it with the command
`unblock-proxy.sh dns --redsocks --web-admin`
All the sites that I added to it do not load with the browser, but when
cmd
I get the domain nslookup and it returns correctly
I checked on several devices and it is the same problem

**Comment by koloner** [comment] 2024-01-21 20:03
If it is possible, give me an email or a communication method, I need a service similar to yours for a project, and today I tested your service, it worked well, but after adding the domain, it stopped working.

**Comment by koloner** [comment] 2024-01-21 21:57
![Screenshot 2024-01-22 012553](https://github.com/suuhm/unblock-proxy.sh/assets/17069284/a9fcaf7e-a987-4a4f-b377-82dd51ecb18d)
this error
when not give any error
again not proxy dns requst
and show apache page in my server

**Comment by suuhm** [comment] 2024-01-21 22:24
Do you get any issues and error when you put the domain in the `domains.lst` file?

You have maybe a buggy dnsmasq version so somerhing is killing the process here, need more log or strace infos here if possible.

Also you can try to disable dnsmasq at start with `systemctl disable dnsmasq` than reboot

**Comment by koloner** [comment] 2024-01-21 22:48
Successful saved and restarted, now you can go back!

This message always appears when adding

Error when I added a domain
`Jan 21 23:44:57 dnsmasq[1863]: exiting on receipt of SIGTERM`

And I typed these two commands and executed the command again, it was activated correctly
```
systemctl disable sniproxy
systemctl disable dnsmasq
unblock-proxy.sh dns --redsocks --web-admin
```

**Comment by koloner** [comment] 2024-01-22 09:37
Hello again, my problem was almost solved last night with the commands I sent, but now I have a problem again, so that sniproxy does not connect and port 443 does not open, how can I check this and fix it?

When it was correct, it stopped two sniproxy processes when it wanted to reset

**Comment by suuhm** [comment] 2024-01-22 10:24
hmm seems to be a strange problem with your os or iptables maybe..
can you tell me which distribution you`re using?

you can also reset your tables first `unblock-proxy.sh -R` or better a fully restart of your os.
After that therse should nothing block the connect to the ports.

Also please check your `/var/log/syslog` and `/var/log/messages` or post it here if you have some issues

**Comment by koloner** [comment] 2024-01-22 16:15
Tested on Ubuntu 20 and Ubuntu 22
Both have error can you fix this for me i need to add feature

**Comment by koloner** [comment] 2024-01-22 16:59
Every time I try to activate the service, but this service is not activated and that's why it doesn't work

![image](https://github.com/suuhm/unblock-proxy.sh/assets/17069284/435b3bf5-c3be-43c5-8b75-a4ec1adc95b8)

![image](https://github.com/suuhm/unblock-proxy.sh/assets/17069284/80890891-bf04-4a0a-b12e-615dcb1961ca)

**Comment by suuhm** [comment] 2024-01-22 17:37
Did you have the same problems with the domains.lst file or only by entering in webinterface?

It seems you have autostart on for dnsmasq . Can you please disable it with `systemctl disbale dnsmasq && systemctl daemon-reload`

and also give please output of: `systemctl list-units --all`

and Output of `journalctl -xeu sniproxy`

**Comment by koloner** [comment] 2024-01-22 17:56
my domians.lst
```
## DOMAINS YOU WANT TO USE A PROXY
#
## ONE DOMAIN PER LINE!!

myip.is
ifconfig.co
```
output of: `systemctl list-units --all`

[output.txt](https://github.com/suuhm/unblock-proxy.sh/files/14013751/output.txt)

output of: `journalctl -xeu sniproxy`

[sni.txt](https://github.com/suuhm/unblock-proxy.sh/files/14013754/sni.txt)

Disable auto start dnsmasq

**Comment by suuhm** [comment] 2024-01-22 19:39
it looks like the problem is, that there is service blocking port 80 and port 443.

you can check with `ss -tulpn | grep -E '80|443'` which service is blocking

**Comment by koloner** [comment] 2024-01-22 20:44
![image](https://github.com/suuhm/unblock-proxy.sh/assets/17069284/afb03d66-d5a0-43d9-9a53-ea7da577524a)

**Comment by suuhm** [comment] 2024-01-22 22:24
you have to stop apache or disable the virtual host on port 80 to get your sniproxy work

**Comment by koloner** [comment] 2024-01-22 23:45
Yes, the problem is that I install php with the command you posted above and it automatically creates itself on port 80, so how can I bring up the management panel on a port other than 80 and without the need to install apache

**Comment by suuhm** [comment] 2024-01-23 08:25
just do this:

`apt purge apache2 apache2-bin && apt install php-fpm php-cli`

**Comment by suuhm** [comment] 2024-01-24 20:55
If you got success please close the issue thanks

**Comment by koloner** [comment] 2024-01-25 00:06
Yes, the problem is solved, thanks
I would like to add this project as a private feature if possible.

**Comment by suuhm** [comment] 2024-01-25 10:09
All right , feel free to do 👍

**Closed as completed** 2024-01-25 10:09 UTC
